import 'package:flutter/material.dart';

const List songs = [
  {
    "img": "assets/haledil.jpg",
    "title": "Hale Dil",
    "description": "MURDER 2",
    "song_count": "100 songs",
    "date": "about 19 hr",
    "color": Color(0xFF545270),
    "song_url": "theme_01.mp3",
    "songs": [
      {"title": "Imagination"},
      {"title": "Home_"},
      {"title": "Do I Wanna Know?"},
      {"title": "Whiskey Sour"},
      {"title": "Decisions"},
      {"title": "Trees"},
      {"title": "Earth"},
    ]
  },
  {
    "img": "assets/aedil.jpg",
    "title": "Ae Dil ha Mushkil",
    "description": "Ae Dil",
    "song_count": "324 songs",
    "date": "about 14 hr",
    "color": Color(0xFF64849c),
    "song_url": "theme_02.mp3",
    "songs": [
      {"title": "Kaleidoscope"},
      {"title": "Larks"},
      {"title": "Homeland"},
      {"title": "Une Danse"},
      {"title": "Almonte"},
      {"title": "Days Like These"},
      {"title": "In questo momento"},
    ]
  },
  {
    "img": "assets/kabir.jpg",
    "title": "Bekhayali",
    "description": "KABIR SINGH",
    "song_count": "195 songs",
    "date": "about 10 hr",
    "color": Colors.red,
    "song_url": "theme_03.mp3",
    "songs": [
      {"title": "Escaping Time"},
      {"title": "Just Look at You"},
      {"title": "Flowing"},
      {"title": "With Resolve"},
      {"title": "Infinite Sustain"},
      {"title": "Ingénue"},
      {"title": "Hidden Chambers"},
    ]
  },
  {
    "img": "assets/sajni.jpg",
    "title": "Sajni",
    "description": "LAAPATAA LADIES",
    "song_count": "599 songs",
    "date": "about 21 hr",
    "color": Color(0xFFbad6ec),
    "song_url": "theme_04.mp3",
    "songs": [
      {"title": "Imagination"},
      {"title": "Home_"},
      {"title": "Do I Wanna Know?"},
      {"title": "Whiskey Sour"},
      {"title": "Decisions"},
      {"title": "Trees"},
      {"title": "Earth"},
    ]
  },
  {
    "img": "assets/animal.jpg",
    "title": "Phle bhi Main",
    "description": "ANIMAL",
    "song_count": "317 songs",
    "date": "about 11 hr",
    "color": Colors.grey,
    "song_url": "theme_05.mp3",
    "songs": [
      {"title": "Imagination"},
      {"title": "Home_"},
      {"title": "Do I Wanna Know?"},
      {"title": "Whiskey Sour"},
      {"title": "Decisions"},
      {"title": "Trees"},
      {"title": "Earth"},
    ]
  },
  {
    "img": "assets/farzi.png",
    "title": "Paisa Hai Toh",
    "description": "FARZI",
    "song_count": "130 songs",
    "date": "about 7 hr",
    "color": Color(0xFFa4c4d3),
    "song_url": "theme_06.mp3",
    "songs": [
      {"title": "Imagination"},
      {"title": "Home_"},
      {"title": "Do I Wanna Know?"},
      {"title": "Whiskey Sour"},
      {"title": "Decisions"},
      {"title": "Trees"},
      {"title": "Earth"},
    ]
  },
  {
    "img": "assets/villain.jpg",
    "title": "Zaroorat",
    "description": "EK VILLAIN",
    "song_count": "50 songs",
    "date": "about 17 hr",
    "color": Color.fromARGB(134, 145, 10, 22),
    "song_url": "theme_07.mp3",
    "songs": [
      {"title": "Kaleidoscope"},
      {"title": "Larks"},
      {"title": "Homeland"},
      {"title": "Une Danse"},
      {"title": "Almonte"},
      {"title": "Days Like These"},
      {"title": "In questo momento"},
    ]
  },
  {
    "img": "assets/dhillon.jpg",
    "title": "Insane",
    "description": "Ap Dhillon",
    "song_count": "69 songs",
    "date": "2 hr 14 min",
    "color": Colors.yellow,
    "song_url": "theme_08.mp3",
    "songs": [
      {"title": "Escaping Time"},
      {"title": "Just Look at You"},
      {"title": "Flowing"},
      {"title": "With Resolve"},
      {"title": "Infinite Sustain"},
      {"title": "Ingénue"},
      {"title": "Hidden Chambers"},
    ]
  },
  {
    "img": "assets/afsanay.jpg",
    "title": "Afsanay",
    "description": "Talha Anjum",
    "song_count": "60 songs",
    "date": "3 hr 25 min",
    "color": Color(0xFFd9e3ec),
    "song_url": "theme_09.mp3",
    "songs": [
      {"title": "Imagination"},
      {"title": "Home_"},
      {"title": "Do I Wanna Know?"},
      {"title": "Whiskey Sour"},
      {"title": "Decisions"},
      {"title": "Trees"},
      {"title": "Earth"},
    ]
  },
];
